plugins { id 'com.android.application' }

android {
    namespace 'com.nemerpus.lateralwheelie'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nemerpus.lateralwheelie'
        minSdk 26
        targetSdk 35
        versionCode 33
        versionName '1.0.14'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}
